default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: API

  username: postgres
  password: root

  port: 5434

# test:
#   <<: *default
#   database: API_test

#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

#
# production:
#   <<: *default
#   database: API_production
#   username: API
#   password: <%= ENV["API_DATABASE_PASSWORD"] %>
